<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Agenda de contactos Interesse&copy;2014</title>
  <?php echo $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.css') ?>
  
</head>
<body>
  
<div class="container">

 <?php echo $this->layout()->content ?>

</div><!-- /.container -->


</body>
</html>